import pyautogui
import time
import pandas as pd

x = 0
y = 1

caminho = r"//depo0903/gpa$/PAC/Daniel Menezes/Python/RESSUPRIMENTO/PRODUTOS.xlsx"
tabela = pd.read_excel(caminho)
df = pd.DataFrame(tabela)
print(df)

pyautogui.press("win")
time.sleep(2)
pyautogui.write("OPERA")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(3)
pyautogui.click(239, 62)
time.sleep(3)
pyautogui.write("manhattan")
time.sleep(2)
pyautogui.hotkey("down")
pyautogui.hotkey("down")
pyautogui.hotkey("down")
pyautogui.hotkey("down")
pyautogui.hotkey("down")
pyautogui.hotkey("down")
pyautogui.hotkey("down")
pyautogui.hotkey("down")
pyautogui.hotkey("down")
time.sleep(1)
pyautogui.hotkey("enter")
pyautogui.press("enter")
time.sleep(3)
pyautogui.hotkey("enter")
pyautogui.press("enter")
pyautogui.click(5, 100)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.click(498, 449)
pyautogui.write("5446902")
pyautogui.click(716, 451)
pyautogui.write("Gpa@84232001668")
time.sleep(2)
pyautogui.hotkey("enter")
pyautogui.press("enter")
time.sleep(1)
pyautogui.leftClick(57, 85)
time.sleep(1)
pyautogui.write("Locais de Picking")
time.sleep(1)
pyautogui.press("enter")
time.sleep(2)
pyautogui.leftClick(946, 132)


while True:
    time.sleep(1)
    plu = df.iloc[x, y]
    pyautogui.leftClick(260, 194)
    time.sleep(1)
    print(plu)
    pyautogui.write(str(plu))
    time.sleep(1)
    pyautogui.leftClick(1095, 195)
    time.sleep(1)
    pyautogui.leftClick(74, 324)
    time.sleep(1)
    pyautogui.leftClick(1119, 704)
    time.sleep(1)
    pyautogui.leftClick(206, 665)
    time.sleep(1)
    pyautogui.leftClick(899, 702)
    time.sleep(1)
    pyautogui.leftClick(62, 148)
    time.sleep(1)
    pyautogui.doubleClick(215, 193)
    time.sleep(1)
    pyautogui.hotkey("backspace")
    x = x + 1 
    print(x)
